### ISSUE TITLE
capnp file with C++ namespace annotation

### ISSUE THREAD

**Issue by Armael** [pelzlpj/capnp-ocaml#6]
Hi,

Maybe this is not properly an issue, but in this case it should probably be documented.
Here's the thing: I defined a .capnp file, that will be used with both the c++ compiler provided with the capnp compiler, and capnp-ocaml. As I want the c++ generated code to lay in a separate namespace, I added the lines from the cap'n proto documentation (https://capnproto.org/cxx.html#setting-a-namespace):

```
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("foo");
```

and put them at the beginning of my .capnp file.

Now, when I try to compile it using capnp-ocaml, I get the following error:

```
File "guiCommands.mli", line 7, characters 38-45:
Error: Unbound module C2b2b
```
(where my capnp file is `guiCommands.capnp`)

Maybe unrelated, but surprisingly enough, if I comment the second line, capnp-ocaml fails raising a `Not_found` exception.

**Comment by pelzlpj** [comment]
The behavior with "using Cxx" is kind of unfortunate, and is something I'd like to improve since the capnproto.org documentation has many examples that rely on this declaration. But in the meantime, here's the explanation and the workaround.

The schema statement 'import "/capnp/c++.capnp"' is treated as a reference to an OCaml module. OCaml naming conventions sadly don't allow for a module called "C++", so capnp-ocaml does some name mangling and ends up with "C2b2b" (using conversion '+' == 0x2b).

What you need to do is separately compile c++.capnp from the Cap'n Proto libraries, which will generate an OCaml module for you. Then you can reference that module when you build your own schema file.

The Not_found exception sounds like a more straightforward bug. This happens when you comment out "$Cxx.namespace("foo");" ?

**Comment by Armael** [comment]
Ok, thanks a lot for the explanations, and the workaround! 

As for the `Not_found` exception, it happens indeed if I comment out "$Cxx.namespace("foo");". The error is then:

```
capnp compile -o ocaml ../capnp/guiCommands.capnp
Uncaught exception:
  
  Not_found

Raised at file "src/core_hashtbl.ml", line 255, characters 29-38
Called from file "src/core_hashtbl.ml", line 257, characters 4-47
Called from file "src/core_list.ml", line 857, characters 21-28
```

**Comment by pelzlpj** [comment]
The `Not_found` exception looks like a separate issue, so let's track it over here: https://github.com/pelzlpj/capnp-ocaml/issues/8

**Comment by pelzlpj** [comment]
It looks like capnp-c++ requires separate compilation of an imported schema only when the importer references declarations found in the import.  In particular, importing `c++.capnp` does not force inclusion of `c++.capnp.h` because the import only results in annotations and not declarations.

This might be a good policy for capnp-ocaml as well.

**Comment by pelzlpj** [comment]
As of https://github.com/pelzlpj/capnp-ocaml/commit/f9a50430fc48f1dd49955fc6019f4035903079bf, capnp-ocaml should omit references to imports which are not used within the generated code.  In particular, an import of `"/capnp/c++.capnp"` no longer generates a reference to a module with the confusing name of `C2b2b`, and there should be no need to separately compile that imported schema file.

**Comment by Armael** [comment]
Neat. Thanks a lot!
